#  docker run -d --name taskmanagercontainer -v $(pwd):/app:ro -v /app/node_modules --env-file .env -p 4000:4000 taskmanager
version: "3"
services:
  app:
    container_name: "taskmanagercontainer_dev"
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - node_env=development
# docker-compose -f docker-compose.dev.yml up -d
# docker-compose -f docker-compose.dev.yml down
# docker-compose -f docker-compose.dev.yml exec app /bin/bash
