#  docker run -d --name taskmanagercontainer -v $(pwd):/app:ro -v /app/node_modules --env-file .env -p 4000:4000 taskmanager
version: "3"
services:
  app:
    container_name: "taskmanagercontainer"
    build: .
    volumes:
      - .:/app:ro
      - /app/node_modules
    ports:
      - "4000:4000"
    env_file:
      - .env
