#  docker run -d --name taskmanagercontainer -v $(pwd):/app:ro -v /app/node_modules --env-file .env -p 4000:4000 taskmanager
version: "3"
services:
  app:
    container_name: "taskmanagercontainer_prod"
    build: .
    volumes:
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - node_env=production
    env_file:
      - .env
# docker-compose -f docker-compose.prod.yml up -d
# docker-compose -f docker-compose.prod.yml down
